# Generated by Django 5.0.6 on 2024-05-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogdata',
            new_name='blog',
        ),
    ]
