# Generated by Django 5.0.6 on 2024-05-25 05:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0002_rename_blogdata_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_data',
            fields=[
                ('Blog_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=3)),
                ('Blog_Name', models.CharField(max_length=30)),
                ('Blog', models.TextField()),
                ('Blog_Image', models.ImageField(max_length=250, null=True, upload_to='media/blogimg')),
            ],
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
