# Generated by Django 5.0.6 on 2024-05-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0003_blog_data_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='User_Name',
            field=models.CharField(max_length=30),
        ),
    ]
