# Generated by Django 5.0.6 on 2024-05-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0004_alter_blog_data_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='Blog_Image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/blogimg'),
        ),
    ]
