# Generated by Django 5.0.6 on 2024-05-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0005_alter_blog_data_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_data',
            name='Blog_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='blog_data',
            name='User_Name',
            field=models.CharField(editable=False, max_length=30),
        ),
    ]
