# Generated by Django 5.0.6 on 2024-05-27 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0006_blog_data_blog_date_alter_blog_data_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_data',
            name='Favourite',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog_data',
            name='Id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog_data',
            name='Blog_Id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
