# Generated by Django 5.0.6 on 2024-05-27 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdata', '0008_alter_blog_data_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_data',
            name='Favourite',
        ),
        migrations.AddField(
            model_name='blog_data',
            name='Favourite',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
